apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-exposer
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: app-exposer
  template:
    metadata:
      labels:
        de-app: app-exposer
        app: de
    spec:
      serviceAccountName: app-exposer
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: de-app
                operator: In
                values:
                - app-exposer
            topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: jobservices.yml
                path: service.yml
        - name: nats-client-tls
          secret:
            secretName: nats-client-tls
        - name: nats-services-creds
          secret:
            secretName: nats-services-creds
        - name: nats-configuration
          emptyDir: {}
      containers:
      - name: app-exposer
        image: harbor.cyverse.org/de/app-exposer
        resources:
          requests:
            cpu: "1m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        args:
          - --namespace
          - "$(APP_EXPOSER_NAMESPACE)"
          - --user-suffix
          - "@$(USER_SUFFIX)"
          - --log-level
          - debug
        env:
          - name: APP_EXPOSER_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CLUSTER
            value: "1"
          - name: USER_SUFFIX
            valueFrom:
              secretKeyRef:
                name: configs
                key: USER_SUFFIX
          - name: OTEL_TRACES_EXPORTER
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_TRACES_EXPORTER
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
          - name: DISCOENV_NATS_CLUSTER
            valueFrom:
              secretKeyRef:
                name: configs
                key: NATS_URL
        ports:
          - name: listen-port
            containerPort: 60000
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
          - name: service-configs
            mountPath: /etc/cyverse/de/configs
            readOnly: true
          - name: nats-client-tls
            mountPath: /etc/nats/tls
            readOnly: true
          - name: nats-services-creds
            mountPath: /etc/nats/creds
            readOnly: true
          - name: nats-configuration
            mountPath: /etc/cyverse/de/env
            readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: app-exposer
spec:
  selector:
    de-app: app-exposer
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
# ---
# apiVersion: batch/v1beta1
# kind: CronJob
# metadata:
#   name: app-exposer-curl
# spec:
#   schedule: "*/1 * * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: app-exposer-curl
#             image: curlimages/curl:7.69.1
#             args:
#             - -L
#             - -X
#             - POST
#             - http://app-exposer/vice/apply-labels
#           restartPolicy: OnFailure
          
