apiVersion: apps/v1
kind: Deployment
metadata:
  name: jex-adapter
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: jex-adapter
  template:
    metadata:
      labels:
        de-app: jex-adapter
        app: de
    spec:
      serviceAccount: configurator
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: de-app
                operator: In
                values:
                - jex-adapter
            topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: jobservices.yml
                path: jobservices.yml
        - name: nats-client-tls
          secret:
            secretName: nats-client-tls
        - name: nats-services-creds
          secret:
            secretName: nats-services-creds
      containers:
      - name: jex-adapter
        image: harbor.cyverse.org/de/jex-adapter
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
          - name: service-configs
            mountPath: /etc/iplant/de
            readOnly: true
          - name: nats-client-tls
            mountPath: /etc/nats/tls
            readOnly: true
          - name: nats-services-creds
            mountPath: /etc/nats/creds
            readOnly: true
        resources:
          requests:
            cpu: "1m"
            memory: "128Mi"
            ephemeral-storage: "100Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
        env:
          - name: DISCOENV_NATS_CLUSTER
            valueFrom:
              secretKeyRef:
                name: configs
                key: NATS_URLS
          - name: OTEL_TRACES_EXPORTER
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_TRACES_EXPORTER
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        args:
          - --config
          - /etc/iplant/de/jobservices.yml
          - --log-level
          - debug
        ports:
          - name: listen-port
            containerPort: 60000
        livenessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: jex-adapter
spec:
  selector:
    de-app: jex-adapter
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
