apiVersion: apps/v1
kind: Deployment
metadata:
  name: qms
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: qms
  template:
    metadata:
      labels:
        de-app: qms
    spec:
      serviceAccount: configurator
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: de-app
                    operator: In
                    values:
                      - qms
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: jobservices.yml
                path: service.yml
      containers:
        - name: qms
          image: harbor.cyverse.org/de/qms
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: timezone
                  key: timezone
            - name: QMS_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: QMS_DATABASE_URI
            - name: QMS_DATABASE_MIGRATE
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: QMS_DATABASE_MIGRATE
            - name: QMS_DATABASE_REINIT
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: QMS_DATABASE_REINIT
            - name: QMS_USERNAME_SUFFIX
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: USERNAME_SUFFIX
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_TRACES_EXPORTER
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
          resources:
            requests:
              cpu: "1m"
              memory: "128Mi"
              ephemeral-storage: "100Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "100Mi"
          volumeMounts:
            - name: service-configs
              mountPath: /etc/cyverse/de/configs
              readOnly: true
          ports:
            - name: listen-port
              containerPort: 9000
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: qms
spec:
  selector:
    de-app: qms
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
