apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-status-to-apps-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      de-app: job-status-to-apps-adapter
  template:
    metadata:
      labels:
        de-app: job-status-to-apps-adapter
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: de-app
                    operator: In
                    values:
                      - job-status-to-apps-adapter
              topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: jobservices.yml
                path: jobservices.yml
      containers:
        - name: job-status-to-apps-adapter
          image: harbor.cyverse.org/de/job-status-to-apps-adapter
          volumeMounts:
            - name: service-configs
              mountPath: /etc/iplant/de
              readOnly: true
          resources:
            requests:
              cpu: "1m"
              memory: "128Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "1Gi"
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: timezone
                  key: timezone
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_TRACES_EXPORTER
            - name: OTEL_EXPORTER_JAEGER_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: configs
                  key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
          args:
            - --config
            - /etc/iplant/de/jobservices.yml
            - --batch-size
            - "20"
